" plug deps
source $HOME/.config/nvim/plugins.vim

" responsible for keeping current color scheme, under external script control
" see ../scripts/toggle_dark_theme.sh
source $HOME/.config/nvim/color.vim

" custom scripts
source $HOME/.config/nvim/scripts.vim

" base conf
source $HOME/.config/nvim/conf.vim

" key maps
source $HOME/.config/nvim/keymaps.vim

" ctrlP wildignore
source $HOME/.config/nvim/wildignore.vim

" config for LSP
source $HOME/.config/nvim/lsp.vim
